### PR TITLE
Re-build the levenshtein

### PR DESCRIPTION
**Pull request by Huy-Ngo**

### CODE REVIEW

**Comment by Huy-Ngo** [comment]
Well since we're using a walled garden platform what do you mean by portable?

**Comment by Huy-Ngo** [comment]
> sha256sum: command not found

Aight that's a linux thing

**Comment by Huy-Ngo** [comment]
> Container action is only supported on Linux

My disappointment is immeasurable and my day is ruined

**Comment by Huy-Ngo** [comment]
So here are how to generate SHA256 checksum on [Windows](https://ladedu.com/how-to-verify-a-md5-or-sha-checksum-on-windows-10/) and [Mac](https://ladedu.com/how-to-verify-an-md5-or-sha-checksum-on-a-mac/). I guess we need conditional tasks based on environment

**Comment by McSinyx** [comment]
> Well since we're using a walled garden platform what do you mean by portable?

Oh LOL I wasn't talking to you, was subcommenting on the action's author, didn't notice that there's a PR and that they display commits' comments here SMFH.

**Comment by Huy-Ngo** [comment]
> was subcommenting on the action's author

Oh lol, I share the same disappointment.

**Comment by Huy-Ngo** [comment]
Btw don't merge PR. Otherwise the number of wheels to build would accumulate quickly

**Comment by Huy-Ngo** [comment]
Wait, how are the checksums published? Shouldn't we release the sums as well?

**Comment by McSinyx** [comment]
I think you made some typo in the conditionals because none of them run for any job.

**Comment by Huy-Ngo** [comment]
Dunno, guess I'll printf-debug from remote

**Comment by Huy-Ngo** [comment]
> Run echo $RUNNER_OS
> Linux

It's correct tho

**Pull request closed without merging**
